services:
  db:
    image: postgres:15-alpine
    container_name: rental_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rental_db
    ports:
      - "8853:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend  # แก้จาก ./backend เป็น ../backend
      dockerfile: Dockerfile
    container_name: rental_backend
    ports:
      - "8852:8852"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:password123@db:5432/rental_db?schema=public"
      PORT: 8852
    volumes:
      - ../backend:/usr/src/app # แก้ path
      - /usr/src/app/node_modules
    command: npm run start:dev

  client:
    build:
      context: ../frontend-client # แก้ path
      dockerfile: Dockerfile
    container_name: rental_client
    ports:
      - "8850:8850"
    volumes:
      - ../frontend-client:/app # แก้ path
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 8850

  backoffice:
    build:
      context: ../frontend-backoffice # แก้ path
      dockerfile: Dockerfile
    container_name: rental_backoffice
    ports:
      - "8851:8851"
    volumes:
      - ../frontend-backoffice:/app # แก้ path
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 8851

volumes:
  pgdata: